'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PolyMon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to # Monitor status is available through the following $Status object
        '''# Properties: $Status.StatusID, $Status.Status
        '''# The following StatusID values have corresponding Status values:
        '''# 1=OK, 2=WARN, 3=FAIL
        '''
        '''# Monitor Counters are available through the $Counters collection.
        '''# This collection exposes a default Item property which retrieves a Counter by index value, e.g. $Counters(0)
        '''# and also exposes a Counter property that retrieves a Counter by name, e.g. $Counters.Counter(&quot;MyCounterName&quot;)
        '''
        '''# Counter [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PowerShellTemplate() As String
            Get
                Return ResourceManager.GetString("PowerShellTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; Monitor status is available through the Status object
        '''&apos; Properties: Status.StatusID, Status.Status
        '''&apos; The following StatusID values have corresponding Status values:
        '''&apos; 1=OK, 2=WARN, 3=FAIL
        '''
        '''&apos; Monitor Counters are available through the Counters collection.
        '''&apos; This collection exposes a default Item property which retrieves a Counter by index value, e.g. Counters(0)
        '''&apos; and also exposes a Counter property that retrieves a Counter by name, e.g. Counters.Counter(&quot;MyCounterName&quot;)
        '''
        '''&apos; Counter objects expose  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property VBScriptTemplate() As String
            Get
                Return ResourceManager.GetString("VBScriptTemplate", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
